openapi: 3.0.0
info:
  title: User
  version: '1.0'
  description: Data Catalog User API.
  contact:
    name: Kata Sára Cseke
    email: katacseke@gmail.com
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
        description: Unique identifier for user
    get:
      summary: Get a User
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: definitions/UserResponse.yaml
              examples: {}
        '404':
          description: User not found
      operationId: getUser
      description: Get user by ID
    delete:
      summary: Delete a User
      operationId: deleteUser
      responses:
        '204':
          description: User deleted
      description: Delete a specific user
      tags:
        - User
      security:
        - JWT: []
  /users:
    get:
      summary: Get all Users
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./definitions/UserResponse.yaml
              examples: {}
      operationId: getUsers
      description: Get all users.
    post:
      summary: Create a User
      operationId: createUser
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable entity.
      description: Create new user (registration).
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./definitions/UserCreationRequest.yaml
            examples: {}
        description: User information for registration.
      tags:
        - User
  /users/login:
    post:
      summary: Log In
      operationId: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./definitions/UserLoginResponse.yaml
              examples: {}
        '401':
          description: Authentication failed. The username or password is not correct.
      description: Log user into the system.
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./definitions/UserLoginRequest.yaml
            examples: {}
      tags:
        - Authentication
        - User
  /token_info:
    post:
      summary: Token Introspection
      operationId: tokenInfo
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./definitions/TokenInfoResponse.yaml
              examples: {}
      description: It provides information about the token.
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./definitions/TokenInfoRequest.yaml
        description: Contains the token.
      tags:
        - Authentication
        - User
  /user/keys:
    get:
      summary: Get the API Keys of the Authenticated User
      tags:
        - ApiKey
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./definitions/ApiKeyResponse.yaml
      operationId: getUserApiKeys
      description: Lists the api keys for the authenticated user. Requires authentication via access token.
      security:
        - JWT: []
    post:
      summary: Create an API Key for the Authenticated User
      operationId: createUserApiKey
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: ./definitions/ApiKeyCreationResponse.yaml
        '422':
          description: Unprocessable Entity (WebDAV)
      description: Generates a new api key for the authenticated user. Requires that you are authenticated via access token.
      tags:
        - ApiKey
        - User
      security:
        - JWT: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./definitions/ApiKeyCreationRequest.yaml
  '/user/keys/{keyId}':
    parameters:
      - schema:
          type: string
        name: keyId
        in: path
        required: true
        description: The id of the api key.
    get:
      summary: Get an API Key
      tags:
        - ApiKey
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./definitions/ApiKeyResponse.yaml
        '404':
          description: Not Found
      operationId: getUserApiKey
      description: View a single api key of the authenticated user. Requires that you are authenticated via access token.
      security:
        - JWT: []
    delete:
      summary: Delete an API Key
      operationId: deleteUserApiKey
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: Removes an api key from the authenticated user. Requires that you are authenticated via access token.
      security:
        - JWT: []
      tags:
        - ApiKey
        - User
  /users/show_many:
    get:
      summary: Get Many Users by ID
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./definitions/UserResponse.yaml
      operationId: getManyUsersById
      parameters:
        - schema:
            type: array
            items:
              type: string
            uniqueItems: true
          in: query
          name: ids
          description: A comma separated list of ids to query.
          required: true
          style: form
      description: Returns all of the users with the specified IDs.
    parameters: []
  '/users/username/{username}':
    parameters:
      - schema:
          type: string
        name: username
        in: path
        required: true
        description: The username of the user.
    get:
      summary: Get User by Username
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./definitions/UserResponse.yaml
        '404':
          description: Not Found
      operationId: getUserByUsername
      description: Returns the user with the specified username.
  '/users/search/{searchTerm}':
    parameters:
      - schema:
          type: string
          default: ''
        name: searchTerm
        in: path
        required: true
        description: The search term.
    get:
      summary: Search Users by Username
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./definitions/UserResponse.yaml
      operationId: searchUsers
      description: Returns the users which usernames contain the searchTerm.
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Authentication is made by the JWT token sent in the Authorizationheader of the request.
tags:
  - name: Asset
  - name: User
  - name: ApiKey
  - name: Authentication
